//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace PKWebShop.Models
{
    using System;
    using System.Collections.Generic;

    public partial class cart_detail
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        public string CustomerId { get; set; }
        public string ShopId { get; set; }
        public string Type { get; set; } //Product|Discount
        public string ItemId { get; set; }
        [NotMapped]
        public string ItemName { get; set; }
        public string PriceOpt1 { get; set; }
        public string PriceOpt2 { get; set; }
        [NotMapped]
        public double Price { get; set; }
        [NotMapped]
        public string PriceOpt1_name { get; set; }
        [NotMapped]
        public string PriceOpt2_name { get; set; }
        public string Properties { get; set; }
        public int Quantity { get; set; }
        public DateTime? CreatedAt { get; set; }

        [NotMapped]
        public string ProductCode { get; set; }
        [NotMapped]
        public string ProductPicture { get; set; }
        [NotMapped]
        public int? StockQuantity { get; set; }
    }
}
