//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PKWebShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer_score
    {
        public string Id { get; set; }
        public string Name { get; set; }
        public string Products { get; set; }
        public Nullable<int> Product_Qty { get; set; }
        public bool MultipleOnOrder { get; set; }
        public bool MultipleOnCustomer { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public Nullable<int> Score { get; set; }
        public Nullable<double> Order_GranTotal { get; set; }
        public Nullable<System.DateTime> CreateAt { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<bool> Active { get; set; }
        public string LangCode { get; set; }
    }
}
