//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PKWebShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class giasu_teacher
    {
        public string Id { get; set; }
        public string Code { get; set; }
        public string ProvinceOrCity { get; set; }
        public string District { get; set; }
        public string FullName { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string Gender { get; set; }
        public string CardId { get; set; }
        public string Domicile { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Avatar { get; set; }
        public string PictureCardId { get; set; }
        public string School { get; set; }
        public string Majors { get; set; }
        public string SchoolYearbook { get; set; }
        public string Degree { get; set; }
        public string Note { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> CreateAt { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
        public Nullable<bool> Active { get; set; }
        public string OptionId { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public string LangCode { get; set; }
    }
}
