//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PKWebShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class giasu_class
    {
        public string Id { get; set; }
        public string Code { get; set; }
        public string ContactName { get; set; }
        public string ProvinceOrCity { get; set; }
        public string District { get; set; }
        public string HomeNumber { get; set; }
        public string ContactAddress { get; set; }
        public string ContactPhone { get; set; }
        public string ContactEmail { get; set; }
        public string ClassName { get; set; }
        public string Subjects { get; set; }
        public Nullable<int> StudentQty { get; set; }
        public string LessonNumber { get; set; }
        public string LearningTime { get; set; }
        public string DegreeRequired { get; set; }
        public string Note { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> CreateAt { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
        public Nullable<bool> Active { get; set; }
        public string ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedAt { get; set; }
        public string Salary { get; set; }
        public string Teacher { get; set; }
        public Nullable<bool> IsComplete { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public string Status { get; set; }
        public Nullable<int> Demo { get; set; }
        public string LangCode { get; set; }
    }
}
