//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PKWebShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class loyalcustomer
    {
        public string Id { get; set; }
        public string LogoPicture { get; set; }
        public string URL { get; set; }
        public Nullable<int> Order { get; set; }
        public string CustomerName { get; set; }
        public string LangCode { get; set; }
    }
}
