//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations.Schema;

namespace PKWebShop.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    [Table("m_code_info")]
    public partial class MCodeInfo : Entity
    {
        public string Type { get; set; }
        public string Code { get; set; }
        public string Text { get; set; }
        public decimal Value { get; set; }
        public bool Active { get; set; }
    }
}
