//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PKWebShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class n_news_tags
    {
        public string id { get; set; }
        public string tag_name { get; set; }
        public string tag_code { get; set; }
        public string LangCode { get; set; }
        public string seo_title { get; set; }
        public string seo_desc { get; set; }
    }
}
