//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace PKWebShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class order
    {
        public string Id { get; set; }
        public string CustomerId { get; set; }
        public string CustomerName { get; set; }
        public string CustomerPhone { get; set; }
        public string CustomerEmail { get; set; }
        public string ShippingAddress { get; set; }
        public Nullable<double> SubTotal { get; set; }
        public Nullable<double> TaxPercent { get; set; }
        public Nullable<double> Shipping { get; set; }
        public Nullable<double> GrandTotal { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string IP { get; set; }
        public string Browser { get; set; }
        public string Comment { get; set; }
        public Nullable<bool> Complete { get; set; }
        public Nullable<bool> Cancel { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
        public string UpdateBy { get; set; }
        public string Customer_Province { get; set; }
        public string Customer_District { get; set; }
        public string Customer_Ward { get; set; }
        public string Customer_Address { get; set; }
        public string Shipping_Province { get; set; }
        public string Shipping_District { get; set; }
        public string Shipping_Ward { get; set; }
        public string Customer_Comment { get; set; }
        public string Shipping_Name { get; set; }
        public string Shipping_Phone { get; set; }
        public string Status { get; set; }
        public string PaymentMethod { get; set; }
        public Nullable<double> InitialActivationFee { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> AppointmentDate { get; set; }
        public Nullable<double> GuestsPay { get; set; }
        public Nullable<double> ExcessCash { get; set; }
        public Nullable<double> DiscountAmount { get; set; }
        public Nullable<double> DiscountPercent { get; set; }
        public Nullable<decimal> BonusPointsUsed { get; set; }
        public Nullable<decimal> BonusPointsDiscount { get; set; }
        public int BonusPointsGet { get; set; }
        public Nullable<bool> BonusPointsIsGot { get; set; }
        public string GiftCode { get; set; }
        public string Type { get; set; }
        public string LangCode { get; set; }
        public string BonusList { get; internal set; }
        [NotMapped]
        public PaymentData PaymentData { get; set; }
        [NotMapped]
        public List<orders_detail> Details { get; set; }
    }
}
