//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PKWebShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class policy
    {
        public string Id { get; set; }
        public string OrderPolicy { get; set; }
        public string PaymentPolicy { get; set; }
        public string CustomerOrChangePolicy { get; set; }
        public string ShipPolicy { get; set; }
        public string OrderPolicyImage { get; set; }
        public string PaymentPolicyImage { get; set; }
        public string CustomerPolicyImage { get; set; }
        public string ShipPolicyImage { get; set; }
        public string LangCode { get; set; }
    }
}
