//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PKWebShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class popupad
    {
        public string Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string PopupAdsPicture { get; set; }
        public Nullable<System.DateTime> PopupAdsFrom { get; set; }
        public Nullable<System.DateTime> PopupAdsTo { get; set; }
        public string PopupAdsURL { get; set; }
        public string LangCode { get; set; }
        public string ReId { get; set; }
        public bool Active { get; set; }
    }
}
