//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PKWebShop.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class product_option
    {
        [Key]
        [MaxLength(20)]
        public string id { get; set; }
        public string name { get; set; }
        public string parentId { get; set; }
        public string parentName { get; set; }
        public string ProductId { get; set; }
        [NotMapped]
        public List<product_option> ListOption { get; set; }
    }
}
