//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PKWebShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductOptionPrice : Entity
    {
        public string ProductId { get; set; }
        public string LabelName { get; set; }
        public Nullable<double> Price { get; set; }
        public string ReId { get; set; }
        public string LangCode { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
