//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PKWebShop.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class product_option_value
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int id { get; set; }
        public string productId { get; set; }
        [MaxLength(20)]
        public string option1 { get; set; }
        [MaxLength(20)]
        public string option2 { get; set; }
        public decimal price { get; set; }
        public decimal? wholeSalePrice { get; set; }
        public int qty { get; set; }
        public int sold { get; set; }
        public string PropertyId { get; set; }
        public string option1_name { get; set; }
        public string option2_name { get; set; }
    }
}
