//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PKWebShop.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class product_properties
    {
        public string id { get; set; }
        public string name { get; set; }
        public string parrent_properties_id { get; set; }
        public Nullable<bool> is_parrent { get; set; }
        public string url { get; set; }
        public Nullable<bool> active { get; set; }
        public string LangCode { get; set; }
        public string ReId { get; set; }
        [NotMapped]
        public string image { get; set; }
    }
}
