//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PKWebShop.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("tag")]
    public partial class tag
    {
        public string Id { get; set; }
        public string TagName { get; set; }
        public string TagCode { get; set; }
        public string Type { get; set; }
        public string ReId { get; set; }
        public string LangCode { get; set; }
        public string seo_title { get; set; }
        public string seo_desc { get; set; }
    }
}
