//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PKWebShop.Models
{
    using System;
    using System.Collections.Generic;

    using System.ComponentModel.DataAnnotations;
    public partial class uploadmorefile
    {
        [Key]
        public string UploadId { get; set; }
        public string TableId { get; set; }
        public string TableName { get; set; }
        public string FileName { get; set; }
        public string LangCode { get; set; }
    }
}
