//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PKWebShop.Models
{
    using System;
    using System.Collections.Generic;

    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class users_permissions_granted
    {
        [Key, Column(Order = 0)]
        public string UserRole { get; set; }
        public Nullable<int> RoleLevel { get; set; }

        [Key, Column(Order = 1)]
        public string PermissionCode { get; set; }
        public string PermissionName { get; set; }
        public Nullable<bool> Active { get; set; }
    }
}
