//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminPage.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class product_option
    {
        [NotMapped]
        public List<product_option> ListOption { get; set; }
    }
    public partial class product_properties
    {
        [NotMapped]
        public string image { get; set; }
    }
    public partial class orders_detail
    {
        [NotMapped]
        public int OldQuantity { get; set; }
    }
}
