//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminPage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class expens
    {
        public string Id { get; set; }
        public string Vendor_Id { get; set; }
        public string Vendor_Name { get; set; }
        public string ImportTicket_Id { get; set; }
        public Nullable<decimal> Total { get; set; }
        public string PaymentMethod { get; set; }
        public string Reason { get; set; }
        public string Note { get; set; }
        public string Status { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public string Title { get; set; }
    }
}
