//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminPage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class import_ticket
    {
        public string Id { get; set; }
        public string Vendor_Id { get; set; }
        public Nullable<decimal> Total { get; set; }
        public string PayStatus { get; set; }
        public string ImportStatus { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<System.DateTime> ReceivedDate { get; set; }
        public string Note { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public string UpdatedBy { get; set; }
        public string Other_costs { get; set; }
        public string ProductDetail { get; set; }
        public Nullable<bool> IsStorage { get; set; }
        public string Code { get; set; }
    }
}
