//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminPage.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class n_news
    {
        public string NewsId { get; set; }
        public string UrlCode { get; set; }
        public string Name { get; set; }
        public string ParentTopicId { get; set; }
        public string ParentTopicName { get; set; }
        public string TopicId { get; set; }
        public string ToppicName { get; set; }
        public string ShortDescription { get; set; }
        public string Decription { get; set; }
        public string Picture { get; set; }
        public Nullable<bool> Active { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
        public Nullable<int> ViewCount { get; set; }
        public string Tags { get; set; }
        public string Tags_code { get; set; }
        public string TitleWebsite { get; set; }
        public string SEODescription { get; set; }
        public Nullable<int> Order { get; set; }
        public string LangCode { get; set; }
        public string ReId { get; set; }
        public string TableOfContent { get; set; }
        public string ImageAlt { get; set; }

        [NotMapped]
        public List<string> TopicIds
        {
            get { try { return JsonConvert.DeserializeObject<List<string>>(this.TopicId); } catch { return new List<string>(); } }
            set { this.TopicId = JsonConvert.SerializeObject(value); }
        }

        [NotMapped]
        public List<string> ToppicNames
        {
            get
            {
                try { return JsonConvert.DeserializeObject<List<string>>(this.ToppicName); } catch { return new List<string>(); }
            }
            set { this.ToppicName = JsonConvert.SerializeObject(value); }
        }
    }
}
