//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminPage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class packagesetting
    {
        public string Id { get; set; }
        public string WebPackage { get; set; }
        public decimal DiskSize { get; set; }
        public bool GiftCode { get; set; }
        public bool ShippingFee { get; set; }
        public bool PaymentOnline { get; set; }
        public bool MembershipPoints { get; set; }
        public bool SocialLogin { get; set; }
        public bool MultiLanguage { get; set; }
        public bool OrderContact { get; set; }
        public bool MessengerChat { get; set; }
        public bool Warehouse { get; set; }
        public bool Dept { get; set; }
        public Nullable<bool> Vendor { get; set; }
        public Nullable<bool> Comment { get; set; }
    }
}
