//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminPage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public string Id { get; set; }
        public string CategoryId { get; set; }
        public string CategoryName { get; set; }
        public string Code { get; set; }
        public string Picture { get; set; }
        public Nullable<bool> ShowHomePage { get; set; }
        public string Description { get; set; }
        public Nullable<float> Rating { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> CreateAt { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string ProductName { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<double> ListedPrice { get; set; }
        public string ServiceId { get; set; }
        public string ServiceName { get; set; }
        public string ShortDescription { get; set; }
        public Nullable<int> Order { get; set; }
        public Nullable<double> DiscountAmount { get; set; }
        public Nullable<double> DiscountPercent { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
        public string TagID { get; set; }
        public string list_parent_properties { get; set; }
        public string list_properties { get; set; }
        public Nullable<int> Sold { get; set; }
        public string Url { get; set; }
        public string LangCode { get; set; }
        public string ReId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string TagName { get; set; }
        public string OtherLink { get; set; }
        public bool Sellable { get; set; }
        public string VendorId { get; set; }
        public Nullable<int> ValueExchange { get; set; }
        public Nullable<int> WarningQuantity { get; set; }
        public Nullable<double> SalePrice { get; set; }
        public string ImageAlt { get; set; }
        public string SEO_Title { get; set; }
        public string SEO_Desc { get; set; }
        public string Unit { get; set; }
    }
}
