//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminPage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sectionfeaturedetail
    {
        public string Id { get; set; }
        public string SectionCode { get; set; }
        public string SectionName { get; set; }
        public string Description { get; set; }
        public string Picture { get; set; }
        public string Title { get; set; }
        public string SubTitle { get; set; }
        public string URL { get; set; }
        public Nullable<int> VolumeNumber { get; set; }
        public string LangCode { get; set; }
        public Nullable<System.DateTime> CreateAt { get; set; }
        public string ExternalHTML { get; set; }
    }
}
