//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminPage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class service
    {
        public string ServiceId { get; set; }
        public string Name { get; set; }
        public string ShortDescription { get; set; }
        public string Decription { get; set; }
        public string Picture { get; set; }
        public Nullable<int> Order { get; set; }
        public string Quotes { get; set; }
        public string CurrencyUnit { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<double> DiscountAmount { get; set; }
        public Nullable<double> DiscountPercent { get; set; }
        public Nullable<System.DateTime> CreateAt { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
        public string UpdateBy { get; set; }
        public string LangCode { get; set; }
        public string ReId { get; set; }
    }
}
