//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminPage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class shipping_config
    {
        public string Id { get; set; }
        public string ProvineId { get; set; }
        public string ProvineName { get; set; }
        public string Type { get; set; }
        public string DictrictData { get; set; }
        public decimal ShippingFee { get; set; }
        public bool Active { get; set; }
    }
}
