//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminPage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class users_permissions
    {
        public string Code { get; set; }
        public string Name { get; set; }
        public string GroupName { get; set; }
        public Nullable<int> Order { get; set; }
        public bool Status { get; set; }
        public Nullable<bool> Hidden { get; set; }
    }
}
