//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminPage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vn_ward
    {
        public string wardid { get; set; }
        public string name { get; set; }
        public string type { get; set; }
        public string location { get; set; }
        public string districtid { get; set; }
    }
}
