//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminPage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class webconfiguration
    {
        public string Id { get; set; }
        public string CompanyName { get; set; }
        public string Address { get; set; }
        public string Hotline { get; set; }
        public string HotlineTime { get; set; }
        public string FacebookUrl { get; set; }
        public string GoogleUrl { get; set; }
        public string YoutubeUrl { get; set; }
        public string GoogleAnalytics { get; set; }
        public string SEO_MetaDescription { get; set; }
        public string SEO_MetaKeyWord { get; set; }
        public string GoogleMap { get; set; }
        public string ShortAboutUs { get; set; }
        public string LogoPicture { get; set; }
        public string ContactEmail { get; set; }
        public string ChatToolEmbed { get; set; }
        public string WorkTime { get; set; }
        public string LangCode { get; set; }
        public string GoogleClientId { get; set; }
        public string FacebookAppId { get; set; }
        public string FacebookAppVersion { get; set; }
        public string Twitter { get; set; }
        public string Instagram { get; set; }
        public string FacebookClientToken { get; set; }
        public string MailServer { get; set; }
        public string AuthEmail { get; set; }
        public string AuthPassword { get; set; }
        public int Port { get; set; }
        public bool SSL { get; set; }
        public string vnp_TmnCode { get; set; }
        public string vnp_HashSecret { get; set; }
        public string vnp_Version { get; set; }
        public string LogoHeader { get; set; }
        public string LogoFooter { get; set; }
        public string ZaloUrl { get; set; }
        public string TwitterUrl { get; set; }
        public string InstagramUrl { get; set; }
        public string GoogleOrdersStatistic { get; set; }
        public string CompanyPhone { get; set; }
        public string SEO_Meta { get; set; }
        public Nullable<bool> ImportIsStorageDefault { get; set; }
        public string Copyright { get; set; }
        public string ImageShared { get; set; }
        public string FacebookFanpage { get; set; }
        public Nullable<bool> ActiveSales { get; set; }
    }
}
