//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminPage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class whychooseu
    {
        public string Id { get; set; }
        public string Title { get; set; }
        public string Picture { get; set; }
        public string ShortDescription { get; set; }
        public Nullable<int> Order { get; set; }
        public string LangCode { get; set; }
    }
}
