// <auto-generated />
namespace PKWebShop.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class update_db_to_ver102206 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update_db_to_ver102206));
        
        string IMigrationMetadata.Id
        {
            get { return "202208100247543_update_db_to_ver102206"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
