// <auto-generated />
namespace PKWebShop.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class update_cart : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update_cart));
        
        string IMigrationMetadata.Id
        {
            get { return "202211020432030_update_cart"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
